language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://test.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN added via travis settings page
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  make ci